# Generated by Django 3.1.2 on 2020-11-11 16:01

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('created', models.DateTimeField(editable=False)),
                ('updated', models.DateTimeField()),
                ('MondayAM', models.BooleanField(default=False)),
                ('MondayPM', models.BooleanField(default=False)),
                ('TuesdayAM', models.BooleanField(default=False)),
                ('TuesdayPM', models.BooleanField(default=False)),
                ('WednesdayAM', models.BooleanField(default=False)),
                ('WednesdayPM', models.BooleanField(default=False)),
                ('ThursdayAM', models.BooleanField(default=False)),
                ('ThursdayPM', models.BooleanField(default=False)),
                ('FridayAM', models.BooleanField(default=False)),
                ('FridayPM', models.BooleanField(default=False)),
                ('SaturdayAM', models.BooleanField(default=False)),
                ('SaturdayPM', models.BooleanField(default=False)),
                ('Driver', models.BooleanField(default=False)),
                ('Cashier', models.BooleanField(default=False)),
                ('Bagger', models.BooleanField(default=False)),
                ('shifts', models.IntegerField()),
                ('flex', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            bases=('auth.user', models.Model),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
