# Generated by Django 3.1.2 on 2020-10-28 19:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_auto_20201028_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 28, 19, 52, 35, 78586, tzinfo=utc), editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 28, 19, 52, 40, 797241, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 28, 19, 52, 56, 437837, tzinfo=utc), editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 28, 19, 53, 1, 490794, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
