# Generated by Django 3.1.2 on 2020-11-11 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0005_auto_20201110_1536'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
